from typing import Protocol


class VisionRepositoryPort(Protocol):
    def create_session(self, record: dict) -> None: ...
    def close_session(self, session_id: str, ended_at_utc: str, reason: str) -> None: ...
    def save_detection(self, record: dict) -> None: ...
    def save_report(self, record: dict) -> None: ...
    def save_metric_sample(self, record: dict) -> None: ...
    def save_event(self, record: dict) -> None: ...
    def save_error(self, record: dict) -> None: ...
    def query(self, category: str, filters: dict, limit: int, offset: int) -> list[dict]: ...
